# Development
services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - $HOME/.aws:/root/.aws
    command: pnpm dev --host=0.0.0.0

networks:
  bzzz-network:
