# Development
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - bzzz-network

  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - mysql
    # tty: true
    command: pnpm dev --host=0.0.0.0
    # network_mode: "host"
    networks:
      - bzzz-network

networks:
  bzzz-network: {}
