name: SvelteKit Lint

on:
  workflow_dispatch: # For testing
  pull_request:
  push:
    branches:
      - main

env:
  DB_HOST: 'DB_HOST-to-allow-type-check-to-work'
  DB_PORT: 'DB_PORT-to-allow-type-check-to-work'
  DB_ROOT_PASSWORD: 'DB_ROOT_PASSWORD-to-allow-type-check-to-work'
  DB_DATABASE: 'DB_DATABASE-to-allow-type-check-to-work'
  DB_USER: 'DB_USER-to-allow-type-check-to-work'
  DB_PASSWORD: 'DB_PASSWORD-to-allow-type-check-to-work'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: '9.1.2'

      - uses: actions/setup-node@v3
        with:
          node-version: '20.12'
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Checking lint/format errors
        run: pnpm lint

      - name: Checking type errors
        run: pnpm check
